### ISSUE TITLE
Clean UP & Dockerization eos2b6f

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2b6f#2]
Please check that the model is working and refactor it model to the latest eos-template structure.
The workflows have already been updated, you can start by checking if the Actions have run successfully or changes need to be made

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
I have made PR on it, kindly check it. 
Thanks.

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 
The tests are failing, please check

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
Yes, i just check it.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
The model is failing at `ModuleNotFoundError: No module named 'rdkit'`. In my opinion 
This model is also installing rdkit with `conda-forge` which normally causes problem in models what i observed plus this model also uses the same version of rdkit as model `eos9sa2`. And i'm experiencing this exact same problem with model eos9sa2 as well. That's why we switched to `rdkit version 2022.3.1b1` using pip because this version has same descriptors plus same len of descriptors.

What i propose:
We need to switch to `rdkit version 2022.3.1b1` in this case as well and let see that's working or not at `push test` in github actions. What you suggest @GemmaTuron 
Thanks.

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

If the changes you are doing work on your system first (meaning, at --repo_path fetching with the modified dockerfile) you can open a PR. if the modifications to not work on your system then we will need to further dig into it.
Please, attach the log of the error, since the ModuleNotFound only is not that informative, there can be other underlying issues.

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
Right, i'll try it. From error log of https://github.com/ersilia-os/eos2b6f/actions/runs/5369315556/jobs/9740655367 what i understand that it has dependancy issue with rdkit version, by going into detail i got to know that it's the same rdkit version that causes problem in model eos9sa2. 
I'll test it if it will work then i'll open PR on it. Thanks

**Comment by GemmaTuron** [comment]
@ZakiaYahya 

Try the pip install of RDKIT, that should work.
Regarding the issue with the fingerprints, you'll only encounter it again if the rdkit specific fps are being used for featurizing the molecules, in many cases they are not so it should be safe to upgrade version

**Comment by ZakiaYahya** [comment]
@GemmaTuron 
Yes i'm trying `pip install rdkit-pypi==2022.3.1b1` version. Let see if it's working or not.
Thanks.

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
I have changed RDkit version from `conda-forge rdkit==2021.3.4` to `rdkit-pypi==2022.3.1b1` and the model is working inside ersilia with --repo-path. I've open PR on it, kindly check it.
